### ISSUE TITLE
Krom Graphics1 Issue

### ISSUE THREAD

**Issue by Ron5s** [Kode/Kha#1213] opened 2020-06-12 14:14 UTC
Im seeing strange results using Graphics1 with Krom vs HTML5. It runs without errors or warnings for both Krom and Html. Has anyone run into this issue?

Krom:
![krom](https://user-images.githubusercontent.com/7084944/84511896-1109d280-ac7c-11ea-8c5c-53745a78a2b9.png)

HTML5:
![HTML](https://user-images.githubusercontent.com/7084944/84511915-1830e080-ac7c-11ea-9b3b-a9c80f918788.png)

Project.hx Code:
`package;

import kha.math.FastVector3;
import kha.Framebuffer;
import kha.Color;
import kha.Assets;
import kha.graphics1.Graphics;

class Project
{
	var nx:Int = Main.WIDTH;
	var ny:Int = Main.HEIGHT;

	public function new()
	{
		var v1 = new Vec3f(2, 2, 2);
		var v2 = new Vec3f(1, 1, 1);
		trace(v1 - v2);
		trace(v1.dot(v2));
	}

	public function update():Void 
	{
		
	}

	public function render(frames: Array<Framebuffer>): Void 
	{
		var graphics = frames[0].g1;
		graphics.begin();

		for (i in 0 ... nx)
		{
			for (j in new ReverseIterator(ny-1, 0))
			{
				var r = i/nx;
				var g = j/ny;
				var b = 0.2;

				var ir = Std.int(255.99*r);
				var ig = Std.int(255.99*g);
				var ib = Std.int(255.99*b);

				graphics.setPixel(i, ny - j - 1, Color.fromBytes(ir, ig, ib));
			}
		}
		graphics.end();
	}
}

class ReverseIterator 
{
  var end:Int;
  var i:Int;

  public inline function new(start:Int, end:Int) 
  {
    this.i = start;
    this.end = end;
  }

  public inline function hasNext() return i >= end;
  public inline function next() return i--;
}`

Thanks,
Ron

**Comment by RobDangerous** [comment] 2020-06-12 15:17
Works for me with latest Krom and latest Kha on Windows. What versions of Krom and Kha are you using and on what operating system?

**Comment by Ron5s** [comment] 2020-06-14 19:34
Im on Windows 10.  I downloaded the latest Krom files from Krom_bin.  I deleted the Kha repository, re-cloned it and updated the submodules.  I still have the same issue.

**Comment by Ron5s** [comment] 2020-06-15 22:15
An update.  The original screen size I used was 200 by 100, which does not display correctly for me with Krom.  But if I change it to 1920 by 1080 it works.

**Comment by Ron5s** [comment] 2020-06-16 14:11
Another update.  Im not sure if this is the same underlying problem but the following code produces this:

![image](https://user-images.githubusercontent.com/7084944/84785578-7f160880-afa0-11ea-9582-17c83a5b4f40.png)

package;

import kha.Assets;
import kha.Color;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

class Main
{
	public static var WIDTH = 1920;
	public static var HEIGHT = 300;

	static var amplitude : Int = 100;
	static var period : Int = 100;

	static function update(): Void
	{
	}

	static function render(frames: Array<Framebuffer>): Void 
	{
		var graphics = frames[0].g1;
		graphics.begin();

		for (i in 0...frames[0].width)
		{
			var dy = Math.sin(kha.Scheduler.time() + i / period);
			graphics.setPixel(i, 120 + Std.int(amplitude * dy),	kha.Color.White);
		}

		graphics.end();
	}

	public static function main()
	{
		System.start({title: "Project", width: WIDTH, height: HEIGHT}, function (_)
		{
			Assets.loadEverything(function ()
			{
				Scheduler.addTimeTask(function () { update(); }, 0, 1 / 60);
				System.notifyOnFrames(function (frames) { render(frames); });
			});
		});
	}
}

**Comment by RobDangerous** [comment] 2020-06-29 16:58
The sinus wave difference is not a bug - framebuffer content is undefined at the start of render.

**Comment by RobDangerous** [comment] 2020-06-29 18:59
And the other one is now fixed.

**Closed by RobDangerous** 2020-06-29 18:59 UTC
