### ISSUE TITLE
[linux] GL Error 1282

### ISSUE THREAD

**Issue by red-hara** [Kode/Kha#403] opened 2016-09-14 11:42 UTC
I am trying to compile example kha project on linux on linux target.
After succesfully compiling the app falls in endless loop with this error:
`GL Error 1282 ../../Kha/Kore/Backends/OpenGL2/Sources/Kore/VertexBufferImpl.cpp 143`
I use copy of this tutorial: https://github.com/luboslenco/kha3d_examples/tree/master/tutorial01
I can run html5 target without error, but flash fails too.
System: Archlinux (4.7.2-1-ARCH, i686) with latest haxe and updated haxe libraries.

Thank you in advance.

**Comment by RobDangerous** [comment] 2016-09-14 11:47
This fails after the glVertexAttribDivisor call which is a "relatively recent" OpenGL addition (from 2009). What OpenGL driver do you use?

**Comment by red-hara** [comment] 2016-09-14 11:53
I use `mesa-libgl-12.0.2-1` from Arch repositories.

**Comment by OvermindDL1** [comment] 2016-09-14 14:30
Since you are using mesa, if you can look in the output of `glxinfo` it will list the caps you have, see if you have the capability for that feature (or gist the output and link it here?).

**Comment by OvermindDL1** [comment] 2016-09-14 14:32
Also, sad to report, the Intel(R) 915GM is one of the cards on lists that is marked as reporting more caps then it actually has, and failing pretty horribly if they are used, that might be the case here.  Does Kha have a list of broken cards yet to blacklist caps from them?  Might be good to grab one from a large engine if not.

**Comment by red-hara** [comment] 2016-09-14 14:35
Here is glxinfo output: https://gist.github.com/red-hara/290dd60e3ddc8b8ac389506f0297ce7e

**Comment by RobDangerous** [comment] 2016-09-14 14:44
OpenGL version string: 2.1. OK, didn't expect I'd have to go 10 years back.
@OvermindDL1 there is no blacklist but Kha is relatively defensive in what OpenGL features it uses. Not defensive enough though as it seems.

**Comment by red-hara** [comment] 2016-09-14 14:48
Understood. Thank you.

**Comment by RobDangerous** [comment] 2016-09-14 14:51
Oh, doesn't mean I won't fix it. Will need you for some testing though, can't reproduce on my own hardware.

**Comment by OvermindDL1** [comment] 2016-09-14 14:51
@RobDangerous I've had very **very** bad experiences with **many** old Intel cards (and a couple nVidia and ATI, but those are few and far between).  I've always ended up having to have a blacklist, even for some features that are in the base spec that some (*cough*intel*cough*) cards still said they support but actually do not.  Thankfully such cards are fairly ancient now and all 3 vendors do their drivers reporting better now (driver quality not mentioning), but older cards were horrible and they are still around (as you can see).  >.<

**Comment by red-hara** [comment] 2016-09-14 14:54
@RobDangerous, If you want me help you with Kha improvement, I'm at your service.

**Comment by RobDangerous** [comment] 2016-09-14 14:57
Ya, well, let's try to fix all of that. I don't have a large arsenal of computers to test on but I can rely on a small community of developers to make up for that.

**Comment by RobDangerous** [comment] 2017-01-05 13:37
Please test.

**Closed** 2017-01-05 13:37 UTC
