### ISSUE TITLE
`kha.Assets.loadEverything` not asynchronous on CPP targets

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#937] opened 2018-12-22 08:24 UTC
This means `kha.Assets.progress` is inaccessible until after loading has already completed, which makes pre-loader bars impossible.

A potential work-around is to iterate over the asset lists, load each asset individually, track how many have been loaded and are yet to be loaded, and add a short delay between subsequent loads, so that the renderer has a chance to draw the current progress. Not only is this work-around cumbersome and unnecessarily complicated, but it seems to take *much* longer to load everything. Furthermore this method doesn't allow for smooth tweening of the progress bar, only jittery updates during the blips/moments when rendering can occur.

Edit: 

- 4 seconds to load my game using `loadEverything`.
- 21 seconds to load my game using work-around!

Here is how I implemented the work-around:

```
class Loader {
	var _progress : Float = 0; // Number between 0 and 1
	var _total : Int = 0; // Total number of assets to load
	var _loaders : Array<Void -> Void> = []; // Functions to be called, each one loads a single asset

	public function new () {}

	public function load () {
		// On C++ targets, loading is synchronous, so load asset individually so progress
		// bar can be updated/drawn between loads.

		// Populate array of functions that can be called one by one to load each asset
		for(name in kha.Assets.images.names) { _loaders.push(function() { kha.Assets.loadImage(name, imageLoaded); }); }
		for(name in kha.Assets.sounds.names) { _loaders.push(function() { kha.Assets.loadSound(name, soundLoaded); }); }
		for(name in kha.Assets.blobs.names) { _loaders.push(function() { kha.Assets.loadBlob(name, blobLoaded); }); }
		_total = _loaders.length;

		var first = _loaders.pop();
		first(); // Load the first asset and start the chain reaction
	}

	function imageLoaded (image : kha.Image) { assetReady(); }
	function soundLoaded (sound : kha.Sound) { sound.uncompress(soundUncompressed); }
	function soundUncompressed () { assetReady(); }
	function blobLoaded (blob : kha.Blob) { assetReady(); }
	function assetReady () {
		_progress = 1 - (_loaders.length / _total);
		if( _loaders.length == 0 ) {
			end();
		} else {
			// Load the next asset, with a forced delay first to allow the preloader bar to render
			var next = _loaders.pop();
			haxe.Timer.delay(next, 1);
		}
	}

	public function draw () {
		// DRAW PROGRESS BAR FILLED ACCORDING TO RATIO "_progress"
	}

	function end () {
		// START THE GAME
	}
}
```

**Comment by RobDangerous** [comment] 2018-12-22 13:44
That's a duplicate of #683

**Closed by RobDangerous** 2018-12-22 13:44 UTC
