### ISSUE TITLE
Enable headless/offscreen (no display) rendering

### ISSUE THREAD

**Issue by Clockwork-Muse** [Kode/Kha#1253] opened 2020-10-08 16:26 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy an armory project to a docker container for headless/offscreen rendering on Linux, but the engine seems to require some sort of interactive display to be attached (throws errors, but I wouldn't consider this a bug per se).

**Describe the solution you'd like**
Either the ability to compile in "no screen" mode, or adding parameters to turn it off.

I only specifically need this for the Vulkan API, but some people may want OpenGL.

**Describe alternatives you've considered**
Attempting to set up things like the dummy xorg video drivers (for OpenGL) has not gone well.

**Additional context**
Unreal Engine works inside a docker container without the need for complicated container setup, or cross-linking the host/container in various ways.

**Comment by RobDangerous** [comment] 2020-10-08 16:32
Duplicate of Kode/Kinc#564

**Closed by RobDangerous** 2020-10-08 16:32 UTC
