### ISSUE TITLE
iOS: Screen Orientation Not Configurable Via "khafile.js"

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#962] opened 2019-01-19 09:39 UTC
This setting is currently defined in `Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist`. For example, the following patch would lock the app into "portrait" mode:

```diff
diff --git a/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist b/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist
index 521b2e20..f80890d2 100644
--- a/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist
+++ b/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist
@@ -35,8 +35,6 @@
        <key>UISupportedInterfaceOrientations</key>
        <array>
                <string>UIInterfaceOrientationPortrait</string>
-               <string>UIInterfaceOrientationLandscapeLeft</string>
-               <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
        <key>UIViewControllerBasedStatusBarAppearance</key>
        <false/>
```

**Comment by RobDangerous** [comment] 2019-01-19 10:59
Let's make that one of those system specific khafile options.

**Comment by RobDangerous** [comment] 2019-01-19 11:00
Hey, wait a minute. Duplicate of #930.

**Closed by RobDangerous** 2019-01-19 11:00 UTC
