### ISSUE TITLE
Chinese garbled code

### ISSUE THREAD

**Issue by cjmxp** [Kode/Kha#606] opened 2017-06-09 15:36 UTC
kha\make -windows -v vs2013 --run

class Project {
	public function new() {
		System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);
	}

	function update(): Void {
		trace("中文");
	}

	function render(framebuffer: Framebuffer): Void {		
	}
}

Project.hx:14: 涓枃

**Comment by RafaelOliveira** [comment] 2017-06-09 16:10
trace is a haxe function, its not related to Kha. Haxe doesn't have yet support to unicode, but someone started to work on it (see here in "core changes" https://haxe.io/roundups/387/).

**Comment by cjmxp** [comment] 2017-06-11 17:34
Openfl does not have this problem

**Comment by cjmxp** [comment] 2017-06-11 17:36
windows title Can also garbled

system.iniex（“中文”

**Comment by RobDangerous** [comment] 2017-06-11 17:44
I'm sorry but if you want anybody to help, please provide some actual details about what's happening.

**Comment by cjmxp** [comment] 2017-06-11 17:50
Sorry, I don't know English very well. I don't know how to describe it. The settings window is Chinese garbled, and the window title is garbled

**Comment by sh-dave** [comment] 2017-06-12 06:35
As for the System.init call, Kore's init functions take ```const char *``` instead of ```const wchar_t *```.
So instead of the “中文” he gets some random ascii nonsense for a window title.

![image](https://user-images.githubusercontent.com/13007175/27021608-e8672054-4f49-11e7-8590-29c0723283e5.png)

**Comment by RobDangerous** [comment] 2017-06-12 20:46
That's actually fine if const char* is treated as a utf8 string - which happens automatically in all systems but Windows. I've made a little progress and the debugger shows 中文 in a wchar_t* right before it's passed to Windows' CreateWindowExW function but the title seems to be broken still...

**Comment by RobDangerous** [comment] 2017-06-12 20:49
Hm, also doesn't work if I put in an actual constant wchar_t*, at least on my system. @cjmxp, can you test the latest version?

**Comment by cjmxp** [comment] 2017-06-13 06:50
@RobDangerous 

Yes, it can solve the problem, but there seem to be some minor problems

In addition, MAC also has garbled questions, Linux, I don't have a test environment

Besides, is this the problem with trace?
![image](https://raw.githubusercontent.com/cjmxp/images/master/kha-utf8.png)

```
import kha.System;
class Main {
	public static function main() {
		System.init({title: "中文", width: 1024, height: 768}, function () {
			new Project();
		});
	}
}
````

**Comment by RobDangerous** [comment] 2017-06-13 15:28
Added an untested fix for trace right now, please give it a try. Sadly no idea about those additional window title problems though.

**Comment by cjmxp** [comment] 2017-06-14 06:37
The title problem still exists
trace ("中文"); the application crashes directly.

**Comment by RobDangerous** [comment] 2017-06-15 11:22
Please try again, I think it's all fixed now.

**Comment by cjmxp** [comment] 2017-06-16 08:43
The Title problem has been fixed, but trace ("中文") output only the file name: line number, and no other output

trace ("中文") ;
Main.hx:34:

**Comment by RobDangerous** [comment] 2017-06-23 07:15
Try again please. It only worked in the Visual Studio output panel. In an actual shell it's now outputting question marks for me but maybe because the font doesn't support it.

**Comment by cjmxp** [comment] 2017-06-27 11:00
@RobDangerous 
Output is still garbled 
trace ("中文") ;
Main.hx:34:??

**Comment by sh-dave** [comment] 2017-06-27 13:48
Maybe the console font just doesn't support it or a wrong codepage is selected?
I don't even get the correct result in VS output window, only questionmarks when i just ```OutputDebugString(L"中文");``` on my machine.

**Comment by cjmxp** [comment] 2017-06-28 02:05
@RobDangerous  @sh-dave 
The vs 2013 console output is correct. It should be the garbled code caused by node.js
![image](https://raw.githubusercontent.com/cjmxp/images/master/12.png)

**Comment by cjmxp** [comment] 2017-06-28 02:27
@RobDangerous  @sh-dave 
Here comes the new question. The Chinese font cannot be displayed
![image](https://raw.githubusercontent.com/cjmxp/images/master/9.png)
![image](https://raw.githubusercontent.com/cjmxp/images/master/10.png)

**Comment by RobDangerous** [comment] 2017-06-28 12:45
You have to set a different unicode range via g.fontGlyphs.

**Comment by RobDangerous** [comment] 2017-06-28 18:13
And please try trace again with the very latest version (I'm getting rectangles now).

**Comment by cjmxp** [comment] 2017-06-30 07:45
@RobDangerous   thank you.
Trace has been repaired

**Comment by cjmxp** [comment] 2017-11-23 09:51
Mac OSX platform, this problem still exists

**Comment by RobDangerous** [comment] 2017-11-23 17:33
Just the window title?

**Comment by cjmxp** [comment] 2017-11-24 02:46
@RobDangerous Yes!

**Comment by cjmxp** [comment] 2017-11-24 13:52
fontGlyphs

The Unicode range of \u4e00-\u9fa5 in Chinese is very large, resulting in low efficiency of Kha

**Comment by cjmxp** [comment] 2017-12-20 16:42
It seems to be able to improve fontGlyphs, for example, more literal automatic dynamic buffering Glyph

**Comment by RobDangerous** [comment] 2017-12-20 17:05
I'm not sure what that means but I fixed the window title in macOS.

**Comment by RobDangerous** [comment] 2017-12-20 19:30
I can't reproduce the problem in Linux, works fine for me in Ubuntu.

**Comment by cjmxp** [comment] 2017-12-21 02:04
![image](https://raw.githubusercontent.com/cjmxp/images/master/title-osx.png)

**Comment by RobDangerous** [comment] 2017-12-21 07:57
![chinese-linux](https://user-images.githubusercontent.com/379761/34245988-f66df6d0-e62c-11e7-8f95-994bd0691528.png)

**Comment by RobDangerous** [comment] 2018-01-21 17:51
Nothing more I can do here without more info, sorry.

**Closed by RobDangerous** 2018-01-21 17:51 UTC
Labels: waiting for feedback
