### ISSUE TITLE
A Way to Pack Resources Into .exe?

### ISSUE THREAD

**Issue by RubrumExPlaneta** [Kode/Kha#875] opened 2018-09-14 12:29 UTC
I don't know for targets like Flash (I'm 99% sure it's possible, but I'm not an expert) but for Windows/C++, I am 100% sure you can pack the externals files (how Kha currently handles resources) and put them in the .exe file. This probably requires implementing some sort of internal resource loading code in CPP (platform specific).

That, as far as I am concerned, does not belong here. If this is implemented by Kode, this should probably be a new Haxelib that can be used in Kha. If not, maybe some other third party Haxelib can do the job?

I will try and update this post when I find something useful :)

**Comment by RobDangerous** [comment] 2018-09-17 20:17
This should be a koremake and Kore thing. This is a duplicate of #143 though so let's continue there.

**Closed by RobDangerous** 2018-09-17 20:17 UTC
